# name - "TechTrends - Package with Docker"
name: "TechTrends - Package with Docker"
# Trigger on every push to the main branch
on:
  push:
    branches: [ main ]
jobs:
  build:
    # Run the action on the ubuntu-latest operating system
    runs-on: ubuntu-latest
    # For the Docker build and push step:
    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v2
        # setup-qemu - to enable the execution of different multi-architecture containers
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # setup-buildx - to use an extended Docker CLI build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Build and push the image to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: project              # Context should be set to the project directory.
          file: project/Dockerfile      # Reference the Dockerfile for TechTrends application
          platforms: linux/amd64
          push: true
          tags: qursan/techtrends:latest # Push the image to DockerHub with the tag techtrends:latest
